# example netlify.toml
[build]
  command = "yarn"
  functions = "netlify/functions"
  publish = "."

[[functions]]
  name = "organizer"
  path = "functions/organizer.ts"
  command = "npm test"
  test = true